name = "custom-stripe-checkout-worker"
main = "worker.js"
compatibility_date = "2024-05-23"

[vars]
# Your environment variables, e.g., STRIPE_SECRET_KEY, should be set in the Cloudflare Dashboard

[observability]
  [observability.logs]
  enabled = true
  head_sampling_rate = 1
  invocation_logs = true
  persist = true

# [build]
# Removed or left out if not used